### PR TITLE
Review designs and wireframes folder

### PR DESCRIPTION
**Pull request by probuse**
Please Review my Repository. @dorynnamara_twitter @millymelisa97 @anyric @Takia5 @adelinetush @Sebuliba-Adrian
For now,  just review the designs folder and the wireframes folder

### CODE REVIEW

**Review by addi-26 — APPROVED** [review]
Everything looks okay.

**Comment by cnagadya** [comment]
This PR doesnt include all files that have been changed. My guess is because initial commits had been made to master, is that the case?

**Comment by cnagadya** [comment]
Is the 👍 reaction a yes @probuse 

Sorry, poor communication.....it is a yes

**Comment by Sebuliba-Adrian** [comment]
The templates are great. Keep up the good work.

**Review by Takia5 — COMMENTED** [review]
It is as though your menu is not responsive

**Pull request merged**
